### ISSUE TITLE
One questions about the normalization

### ISSUE THREAD

**Issue by iyuner** [Gutianpei/MID#10]
Hi! In the loss function, the original `y_t` is used instead of normalized `y_st_t`. Is there a reason for it? When do we want to use `y_st_t` or `y_t`? Thanks!

https://github.com/Gutianpei/MID/blob/fe1fe84c4b9ae1291250ed4acc47077f6ed2ff5f/models/autoencoder.py#L49

**Comment by Gutianpei** [comment]
Hello, we did not try the normalized y in our experiment, but it does not hurt to try on your end. Since we followed Trajectron++ which used velocity as inputs, the ys has been normalized by converting coordinates to velocity representation.
