### ISSUE TITLE
Question about the configuration file

### ISSUE THREAD

**Issue by ljt1018** [Gutianpei/MID#11]
Thanks for this interesting work! I have tried to reproduce your experimental result using the provided code and configurations and I encountered some issues:

The provided configuration file use transformer encoder layer that has dimension of 256 (instead of 512 mentioned in the paper), I have tried to train the model 10 times using the 256d configuration, the model converge but the resulting ADE results are 0.03 on average higher than (FDE is 0.05-1.0 higher) the result reported in the paper.

However, when I modified the configuration file to change the transfomer encoder layer dimension to 512, it seems the model does not converge very well after training for 90 epochs.

Would you mind providing further instructions on these issues. Thanks a lot in advance!

**Comment by Gutianpei** [comment]
Hello,

Thanks for sharing your result using 256d transformer feature and I'm glad you achieved even better performance. Regarding the 512d feature, I've never had similar problem during experiments, and I'd recommend you using 256d instead since 512d and 256d actually have very similar performance in my experiments.

**Comment by ljt1018** [comment]
Thanks for your reply! 
I am sorry that my previous post caused some misleading, what I mean by "ADE and FDE is higher" actually means the exact evaluation value is higher (in this case, the performance is worser than what you reported in the paper). Consequently, I am wandering whether this performance gap is potentailly caused by using different dimensions of transformer encoder layer(256 vs 512 stated in the paper). My question is: Are you using the provided baseline.yaml to train the MID model or you different settings? I am also working on applying diffusion models to human trajectory prediction problems so I really want to reproduce the similar results using your MID model which would be really helpful for my current research. 
My sincere apology for the misleading from previous post and looking forward to your reply.
Thanks in advance!

**Comment by Gutianpei** [comment]
Hello,

To your question: The YAML file is only an example of how you should run the code. You may change the configuration fits your setting best.
