### ISSUE TITLE
Strong oscillation in ade/fde metrics during training on ETH dataset

### ISSUE THREAD

**Issue by lrq1999** [Gutianpei/MID#12]
Dear Tianpei,

Thanks for your great work! I am writing to you regarding the issue that I have encountered while using your open-source code for training on the ETH dataset. I have noticed a strong oscillation in the ade/fde metrics during the training process, as shown in the attached screenshot. It appears to be quite random, with no clear pattern or trend.

I have used the same hyperparameters as those mentioned in your paper and have fixed the data preprocessing bug mentioned in issue #5 (This may lead to a little bit of performance drop as #5 discusses). However, the results are still not as expected and seem to be consistently fluctuating.

I would appreciate it if you could kindly help me identify the root cause of this issue and provide some guidance on how to resolve it. I have attached the training logs and the test results for your reference, and I am happy to provide any additional information that you may need.

Thank you for your time and assistance in this matter.

Best regards,
Rongqing
![issue](https://user-images.githubusercontent.com/50268469/233889475-971a3b3c-95d8-4314-8759-bc93db2ef743.png)

**Comment by Gutianpei** [comment]
Hello Rongqing,

Thanks for the comment. Your log looks fine and I have the similar oscillation due to the high stochastic nature of original diffusion model. As for your result, I got similar report around 0.5/0.8 for ETH after fixing the bug you mentioned, so I think it's fine too.
