### ISSUE TITLE
“prediction_output_to_trajectories.py” is missing

### ISSUE THREAD

**Issue by Jayzhou3219** [Gutianpei/MID#13]
Thanks to the author for the code, very nice work. But the file “prediction_output_to_trajectories.py” is missing. Would you be convenient to provide it? Here is my gmail email: jianglin1207154288@gmail.com

**Comment by Gutianpei** [comment]
Hello,

I don't quite understand how the “prediction_output_to_trajectories.py” is needed. If you are looking for the prediction_output_to_trajectories function, you can check evaluation/trajectory_utils.py
