### ISSUE TITLE
A question about sampling

### ISSUE THREAD

**Issue by Apocalypse2403** [Gutianpei/MID#14]
In the Appendix Algorithm2 of the paper, the output of the MID Sampling Procedure is the final trajectory prediction y=y0, right? But in your code released on github, the output of sampling is just velocity of the agent, i.e. y_vel. After the sampling there is a intergrate operation to get the final trajectory y_pos. 

I visualized the output of sampling and it doesn`t look like a trajectory. I want to know the intergrate operation is neccesary or not. If yes, why is the output of sampling not the final trajectory result, as shown in Algorithm 2.

**Comment by Gutianpei** [comment]
Hello,

The output is y_vel. After integration, you'll have the distance moved from origin and finally get y_pos.
