### ISSUE TITLE
Confirmation Request: "Stride Value" in sample Function

### ISSUE THREAD

**Issue by jxmmy7777** [Gutianpei/MID#15]
Hello,

Thank you for sharing the code! I have a query regarding the value of the stride parameter in the **sample** function located in `autoencoder.py.` Currently, the stride is set to 100, and I would appreciate clarification on whether the stride value should be 100 or 1. Specifically, I would like to know if the value of 100 is applicable only for the "DDIM" settings. Should we uncomment the line stride = int(100/stride) when using the original "ddpm"?

The code snippet in question is as follows:
```
def sample(self, num_points, context, sample, bestof, point_dim=2, flexibility=0.0, ret_traj=False, sampling="ddpm", step=100):
        traj_list = []
        for i in range(sample):
            batch_size = context.size(0)
            if bestof:
                x_T = torch.randn([batch_size, num_points, point_dim]).to(context.device)
            else:
                x_T = torch.zeros([batch_size, num_points, point_dim]).to(context.device)
            traj = {self.var_sched.num_steps: x_T}
            stride = step
            #stride = int(100/stride)
            for t in range(self.var_sched.num_steps, 0, -stride):
                z = torch.randn_like(x_T) if t > 1 else torch.zeros_like(x_T)
                alpha = self.var_sched.alphas[t]
                alpha_bar = self.var_sched.alpha_bars[t]
                alpha_bar_next = self.var_sched.alpha_bars[t-stride]
                #pdb.set_trace()
                sigma = self.var_sched.get_sigmas(t, flexibility)

                c0 = 1.0 / torch.sqrt(alpha)
                c1 = (1 - alpha) / torch.sqrt(1 - alpha_bar)
```
I kindly request guidance on whether the stride value should be set to 100 or 1 for different settings. If you could provide clarification on the usage of stride in "DDIM" and "ddpm" scenarios, it would be greatly appreciated.

**Comment by Gutianpei** [comment]
Hello,

Thanks for your comment. To only use DDPM, please set "step=100" (as we trained DDPM with 100 steps) in https://github.com/Gutianpei/MID/blob/main/main.py#L43 and the "sampling=ddpm" then you should good to go.

**Comment by jxmmy7777** [comment]
Thanks, the flexibility also be set to 1 right?
