### ISSUE TITLE
Could you provide the config file to reproduce the table on paper?

### ISSUE THREAD

**Issue by Fujiry0** [Gutianpei/MID#17]
Hello,

Thank you for sharing the code! 
I trained the model with `config/baseline.yaml` for stanfrod drone dataset, but it results are not good.
Could you provide the config file to reproduce the table for eth/ucy and stanford dataset on paper?

**Comment by Gutianpei** [comment]
Hello,

I just reproduced the result with the config and get similar result, note that you'll need to regularize the input data by 1/50 for SDD dataset. MID uses stochastic setting and it might cause unstable model performance.
