### ISSUE TITLE
The question of “maximum_history_length"

### ISSUE THREAD

**Issue by ShaokangHi** [Gutianpei/MID#23]
Thanks for your nice work and share your code.

I would like to know your reported results in the paper, is the "maximum_history_length" = 7 or 8? Because I saw you set 7 in your code at ./utils/trajectron_hypers.py.

**Comment by Gutianpei** [comment]
Hello, 

It should be 7 since we use velocity. We adopt this setting from [Trajectron++](https://github.com/StanfordASL/Trajectron-plus-plus/blob/1031c7bd1a444273af378c1ec1dcca907ba59830/experiments/pedestrians/models/eth_vel/config.json).

**Comment by ShaokangHi** [comment]
Thank you for your reply. 
I noticed this was a bug before, but the author of trajectron++ corrected it [maximum_history_length](https://github.com/StanfordASL/Trajectron-plus-plus/issues/10). Now, it is indeed 7.
