### ISSUE TITLE
Questions about models/transformer.py

### ISSUE THREAD

**Issue by dwjh** [Gutianpei/MID#27]
Hello, I have recently been reviewing your code. 

I noticed the presence of Decoder_TRANSFORMER in the models/transformer.py file. Given that you've already implemented a Transformer-based structure (TransformerConcatLinear) as the decoder, I'm curious about the purpose of Decoder_TRANSFORMER. Can it be used interchangeably with TransformerConcatLinear as the decoder, or does it serve a distinct role in the code?

Thanks.

**Comment by Gutianpei** [comment]
This is just testing code, Decoder_TRANSFORMER is not called anywhere.
