### ISSUE TITLE
A question of SDD preprocessing and calculate ADE, FDE

### ISSUE THREAD

**Issue by ShaokangHi** [Gutianpei/MID#29]
Hi,

I noticed that for SDD dataset preprocessing you use:
```
         data['x'] = data['x']/50
         data['y'] = data['y']/50
```
Then calculate ADE, FDE use:
```
                 elif self.config.dataset == "sdd":
                     ade = ade * 50
                     fde = fde * 50
```

I tried to find it at PECnet code, but I didn't find it and still don't know why. Could you please explain it (why 50)?

Thanks in advance!

**Comment by Gutianpei** [comment]
In PECNet the scale for sdd is 1.86, and for eth/ucy is 170. The accurate scale in this cause should be 91, we just set it to 50 for simplicity.

**Comment by ShaokangHi** [comment]
Thank you for your kindly reply!

This means that adjusting the scale, such as using data['x']/91, ade = ade * 91 or data['x']/50, ade = ade * 50, will not affect the model performance, right? I guess it just affects the coordinates of the visualization.

And when we get the scale of 1.86, how do you calculate the precision scale to 91.

Sorry for asking so many questions.

**Comment by Gutianpei** [comment]
170/1.86=91

**Comment by Gutianpei** [comment]
Scale has strong influence to model performance in my experiments, so you might want all datasets under one standard scale to help the model generalize better.

**Comment by ShaokangHi** [comment]
Hi, 

if I would like to get the KDE_nll metric (SDD dataset), do I need "kde*50"? Like the calculation of ADE and FDE.
