### ISSUE TITLE
How to visualize pedestrian trajectories?

### ISSUE THREAD

**Issue by miraclesheephaha** [Gutianpei/MID#9]
Hi @Gutianpei

Thank you for your publishing the code
1.I modified scene_freq_mult_viz：True in baseline.yaml but an AttributeError: 'Environment' object has no attribute 'scenes_freq_mult_prop' will appear.
2.Is there any data set that can be trained and visualized? 
3.How can I actually make the gif file you showed?

Thanks you

**Comment by Gutianpei** [comment]
> Hi @Gutianpei
> 
> Thank you for your publishing the code 1.I modified scene_freq_mult_viz：True in baseline.yaml but an AttributeError: 'Environment' object has no attribute 'scenes_freq_mult_prop' will appear. 2.Is there any data set that can be trained and visualized? 3.How can I actually make the gif file you showed?
> 
> Thanks you

Thanks for the message. 

1. scene_freq_mult_viz is the hyperparameter from Trajectron++ and we never changed it in all the experiments.
2. No. We use ETH/UCH and SDD dataset for visualization.
3. The visualization code is not provided. After obtaine the sampled trajectories (we used 20 samples), you can make a contour map to visualize the distribution at each diffusion step K. Then you can make the GIF.

**Comment by miraclesheephaha** [comment]
Thanks for your reply.
Because I saw the visualization you made and wanted to implement it.
If I want to actually make a visualization, do you have any suggested teaching materials or steps? Because I am a programming novice.

Thank you

**Comment by miraclesheephaha** [comment]
Thank you for your reply and suggestion.
